import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Analytics } from "@vercel/analytics/react"
import "./globals.css";
// import "./katex.min.css"

import Navbar from "../components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Portfolio of Leo Ware",
    //   description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            
            <body className={inter.className}>
                <div className="h-full w-full grid grid-cols-12 grid-rows-10">
                    <div className="grid grid-cols-subgrid col-start-1 col-span-12 row-span-1">
                        <Navbar />
                    </div>
                    <div className="grid grid-cols-subgrid col-span-8 col-start-3 row-start-2 row-span-8">
                        {children}
                    </div>
                </div>
                <Analytics />
            </body>
        </html>
    );
}
