import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Analytics } from "@vercel/analytics/react"
import "./globals.css";
// import "./katex.min.css"

import Navbar from "../components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Portfolio of Leo Ware",
    //   description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="h-full w-full flex flex-col justify-stretch items-stretch">
                    <div className="w-full h-20">
                        <Navbar />
                    </div>
                    <div className="h-full w-full p-10 overflow-y-auto bg-white">
                        {children}
                    </div>
                </div>
                <Analytics />
            </body>
        </html>
    );
}
